config/routes.rb
Rails.application.routes.draw do

	# declare a standard REST resource/model
	# defined routes for all the standard RESTful actions
	# Nested routes
	resources :articles do
		resources :comments
	end

	# get 'welcome/index'

	root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
						length: {minimum: 5}
	mount_uploader :attachment, AttachmentUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
public
	#layout 'standard' #Use standard file layout for views under this controller

	http_basic_authenticate_with name: "Tyrone", password: "demo", except: [:index,:show]
	before_action :find_project, only: [:show, :edit, :update, :destroy]
# rails route HTTP request and URI determine action
	def index
		#List all
		@articles = Article.all
	end

	def show
		#All instance variables are passed to view
		#id passed in
		# @article = Article.find(params[:id])
	end

	def new
	  @article = Article.new
	end

	def edit
		# @article = Article.find(params[:id])
		
	end

	def create
		@article = Article.new(article_params)

		if  @article.save
			redirect_to @article
		else 
			render 'new'
		end
	end

	def update
		# @article = Article.find(params[:id])

		if  @article.update(article_params)
			# routes to show method
			redirect_to @article
		else 
			render 'edit'
		end
	end

	def destroy
		# @article = Article.find params[:id]
		@article.destroy

		redirect_to articles_path
	end

private
	def article_params
		#Strong parameters to create whitelist of allowed params
		params.require(:article).permit(:title, :text, :attachment)
	end
end

def find_project
	@article = Article.find(params[:id])
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	http_basic_authenticate_with name: "Tyrone", password: "demo", except: [:destroy]
	
	def create
		# Find parent article based on foreign key param
		@article = Article.find params[:article_id]
		#  Create comment associated with parent article
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
		
	end

	def destroy
		@article = Article.find params[:article_id]
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end

	private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article , html: { multipart: true } do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
 <!-- bootstrap form class tag -->
 <!-- each label control pair is wrapped in form-group class -->
 <!-- each control is given form-control class -->
 <!-- Possible to make inline forms and horiztonal forms -->
 <!-- Supports range of input types -->
 <!--  -->
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, placeholder: "Give me a name", class: "form-control"  %>
  </div>
 
  <div class="form-group">
    <%= f.label :text %><br>
    <%= f.text_area :text , class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :attachment %><br>
    <%= f.file_field :attachment , class: "form-control"  %>
  </div>
 
  <p>
    <%= f.submit class: "btn btn-default" %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Change Cloud</h1>

<!-- non-empty @article object tells Rails that we want this form to be 
submitted (update) via the (update) PATCH HTTP method  -->
<!-- form_for @article  -->

<!-- render partial view -->
<%= render 'form' %>

<%= link_to 'Upstream', articles_path , class: 'btn btn-default'%>

app/views/articles/index.html.erb
<div id="header">
	<h1>Thoughts</h1>
</div>

<!-- Create nav tabs and show which is active through a list -->
<!-- Use nav-justified to make equal width of parent -->
<ul class="nav nav-tabs " role="tablist">
	 <li class="active">
	 	<%= link_to articles_path do%>
	 		<i class="glyphicon glyphicon-th-list"></i> Thoughts
	 	<% end %>
	 </li>
	<!-- new_article_path Resource for urls -->
	<!-- Links and inputs can be given btn class option, state and size -->
	<li>
		<%= link_to new_article_path do %>
			<!-- Add icons to links using Glyphicons -->
			<i class="glyphicon glyphicon-plus"></i> New thought
		<% end %>
	</li>	
</ul>
<!-- table class provides nice style -->
<!-- tables can be wrapped in table-responsive class for smaller devices -->
<table class="table">
	<!-- Use contextual class for rows and cells -->
	<tr>
		<th>Title</th>
	</tr>

	<% @articles.each do |article| %>
		<tr class="active">
			<!-- <td><%=article.title%></td> -->
			<!-- Tool tip functionality -->
			<!-- Better alt to title html tag -->
			<td>
				<span class="has-tooltip" data-toggle="tooltip" title="<%= "Created on #{article.created_at.strftime("%m/%e/%Y at %w:%M %p")}, Last modified on #{article.updated_at.strftime("%m/%e/%Y at %w:%M %p")}" %>">
				    <%= article.title %>
				</span>
			</td>
			<!--  -->


			<!-- <td><%=article.text%></td> -->

			<!-- Modal component renders pop up to screen -->
			<!-- Requires modal button with data-target
			Modal base class, subclasses - dialog content header title body footer -->
			
			<% if article.text? %>
			  <!-- Button trigger modal -->
			  <button class="btn btn-link" data-toggle="modal" data-target="#article-<%= article.id %>-text">
			    <%=article.title%>
			  </button>

			  <!-- Modal -->
			  <div class="modal fade" id="article-<%= article.id %>-text" tabindex="-1" role="dialog" aria-labelledby="article-<%= article.id %>-label" aria-hidden="true">
			    <div class="modal-dialog">
			      <div class="modal-content">
			        <div class="modal-header">
			          <h4 class="modal-title" id="article-<%= article.id %>-label"><%=article.title%></h4>
			        </div>
			        <div class="modal-body">
			          <%= article.text %>
			        </div>
			        <div class="modal-footer">
			          <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
			        </div>
			      </div>
			    </div>
			  </div>
			<% end %>

			<!--  -->


			<!-- path url helpers -->
			<td>
				<%= link_to "Show", article_path(article) , class: 'btn btn-default btn-xs' %>
				<!-- Popover , requires has-popover class, data-toggle, title and data-content -->
				<% if article.text? %>
					<button type="button" class="btn btn-link has-popover" data-toggle="popover" title="Text" data-content="<%= article.text %>">View Thought (popover)</button>
				<% end %>
			</td>
			
			<td>
				<%= link_to edit_article_path(article) , class: 'btn btn-default btn-xs' do %>
					<i class="glyphicon glyphicon-edit"></i> Change
				<% end %>
			</td>
			
			<td>
				<%= link_to article_path(article),
	              method: :delete,
	              data: { confirm: 'Is this what you want?' } , class: 'btn btn-danger btn-xs' do %>
	              	<i class="glyphicon glyphicon-trash"></i> Destroy
	              <% end %>
	              	<!-- js confirm dialog box -->
	        </td>
		</tr>
	<% end %>
</table>

<%= link_to controller: 'welcome' , class: 'btn btn-default btn-xs' do %>
	<i class="glyphicon glyphicon-home"></i> Upstream
<% end %>

app/views/articles/new.html.erb
<ul class="nav nav-tabs" role="tablist">
	 <li>
	 	<%= link_to articles_path do%>
	 		<i class="glyphicon glyphicon-th-list"></i> Thoughts
	 	<% end %>
	 </li>
	<li class="active">
		<%= link_to new_article_path do %>
			<i class="glyphicon glyphicon-plus"></i> New thought
		<% end %>
	</li>	
</ul>

<h1>New Cloud</h1>

<!-- articles_path url to send form to create action -->
<!-- :article symbol to create formbuilder for article object -->
<!--  form_for :article, url: articles_path do |f| -->

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="row">
	<h3>
		<%= @article.title %>
	</3>

	<!-- Various typography classes can be applied -->
	<p class="lead">
		<%= @article.text %>
	</p>

	<p>
		<%= image_tag(@article.attachment_url , class: " img-responsive img-thumbnail" ) unless @article.attachment.file.nil? %> 
	</p>	
</div>
<div class="row">
	<h3>Remarks</h3>
	<!-- partial view of _comment -->
	<%= render @article.comments %>

	<h4>Make a remark</h4>
	<!-- render partial view -->
	<%= render 'comments/form' %>

	<!-- url helper to edit item -->
	<%= link_to 'Change', edit_article_path(@article) , class: 'btn btn-default'%>
	<!-- articles_path url helper for controller index -->
	<%= link_to 'Upstream', articles_path , class: 'btn btn-default'%>
</div>

app/views/comments/_comment.html.erb
<p>
	<strong>Commenter: </strong>
	<%= comment.commenter %>
</p>
<p>
	<strong>Comment:</strong>
	<%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Remark', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
               <!-- Send delete request nested article_id/comments/id to controller -->
</p>		

app/views/comments/_form.html.erb
<!-- assign form to comment controller create action
Uses array to build nested route article/ForiegnID/comments -->
<%= form_for([@article, @article.comments.build]) do |f| %>
	<div class="form-group">
		<%= f.label :commenter %><br>
		<%= f.text_field :commenter , class: "form-control"  %>
	</div>
	<div class="form-group">
		<%= f.label :body %><br>
		<%= f.text_area :body , class: "form-control"  %>
	</div>
	<p>
		<%= f.submit class: "btn btn-default"  %>
	</p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Awaken to the morning</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!-- Navigation bar for site -->
  <%= render 'shared/navigation' %>
  	<div id="main-container" class="container">
  	<div class="row">
  		<div class="col-md-3">
  			<h3>Awaken to the morning</h3>
  		</div>
  		<div class="col-md-9">
		    <%= yield %>
  		</div>
  	</div>
  		
  	</div>
  </body>
</html>


<!-- Grid layouts
Container class nesting a row class nesting column classes
Rows can be further nested
Can change container to container-fluid

Columns must add up to 12
Columns scale to size 
Columns media from phone to desktop -->

app/views/layouts/standard.html.erb
<!DOCTYPE html>
   <head>
      <title>Awaken to the morning</title>
      <%= csrf_meta_tags %>

      <%= stylesheet_link_tag "style", media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   </head>

   <body id = "tumblr">
      <div id = "container">
         
         

         <div id = "content">
            <%= yield -%>
         </div>

         <div id = "sidebar"></div>
         
      </div>
   </body>
   
</html>

app/views/shared/_navigation.html.erb
<!-- app/views/shared/_navigation.html.erb -->

<!-- Cretae navigation bar -->
<nav class="navbar navbar-default" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="/">Awaken To the Morning</a>
		</div>

		<!-- Dropdown functionality in nav bar -->
		<!-- Add dropdown class -->
		<!-- Add data-toggle="dropdown" to a link or button to toggle a dropdown. -->
		<!-- Add list with class dropdown-menu -->
		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="#">Login</a></li>
		        	<li class="divider"></li>
		        	<li><%= link_to "Posts", controller: 'articles' %></li>
		        	<li class="divider"></li>
		          	<li><%= link_to 'New Thought', new_article_path %></li>
		        </ul>
			</li>
		</ul>
	</div>
</nav>

app/views/welcome/index.html.erb
<div id = "header">
    <h1>In the Mood for thoughts ...</h1>
</div>

<div id= "rootlinks">
	<!-- link using controller -->
	<%= link_to "Posts", controller: 'articles' %>

	<!-- new_article_path resource for urls -->
	<%= link_to "New thought", new_article_path %>
</div>